# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vr_jKt5aeXTP-nYs8cfHs1X4uPdSj0Eo
"""

sabersanbar = 'sim'
gostardefeijoada = 'não'
torcerseleçãobrasileira = 'sim'

if(sabersanbar =='sim' or gostardefeijoada == 'sim' and torcerseleçãobrasileira == 'sim'):
    print('esse é brasileiro')
else:
    print('esse não é brasileiro')

temDentes = 'sim'
temFome ='não'
gosta ='sim'

if temDentes == 'sim':
    TDcondição ='verdadeiro'
elif temDentes =='não':
    TDcondição = 'falso'

if temFome =='não': 
    TFcondição = 'verdadeiro'
elif temFome == 'não':
    TFcondição = 'falso'

if gosta == 'sim' :
    Gcondição = 'verdadeiro'
elif gosta == 'não':
    Gcondição = 'falso'

if TDcondição =='falso' or TFcondição =='falso':
    GTFcondição ='falso'
else:
    GTFcondição ='verdadeiro'

if GTFcondição =='verdadeiro' and TDcondição =='verdadeiro':
    TFcondição='verdadeiro'
else:
    FCondição ='falso'
print(f'a pessoa tem Dentes{TDcondição} e ter fome R: {TFcondição} ou gosta de maçã {Gcondição} = Resposta final falso')